services:

    phmlabs.content.retriever:
        class: phmLabs\TwigContentBundle\Retriever\NullRetriever

    phmlabs.content.twig.extension:
        class: phmLabs\TwigContentBundle\Twig\ContentExtension
        arguments: ['@phmlabs.content.retriever']
        public: false
        tags:
            - { name: twig.extension }

    phmlabs.content.twig.secure.extension:
        class: phmLabs\TwigContentBundle\Twig\SecureExtension
        public: false
        tags:
            - { name: twig.extension }
            -
    phmlabs.content.twig.markup.extension:
        class: phmLabs\TwigContentBundle\Twig\MarkupExtension
        public: false
        tags:
            - { name: twig.extension }

    phmlabs.content.twig.duration.extension:
        class: phmLabs\TwigContentBundle\Twig\DurationExtension
        public: false
        tags:
            - { name: twig.extension }